import React, { useState, useEffect } from 'react';
import { Search, Play, Settings, X, Loader2, Youtube, AlertCircle, User, Calendar, Eye, FileText, ChevronLeft, Download, Copy, Github, RefreshCw, Globe, ShieldCheck, ServerCrash, Network } from 'lucide-react';

// [핵심] Piped 우회 노드 목록 (Swarm Network)
const SWARM_NODES = [
  "https://pipedapi.kavin.rocks",
  "https://api.piped.otter.sh",
  "https://piped-api.garudalinux.org",
  "https://api.piped.privacy.com.de",
  "https://pipedapi.tokhmi.xyz",
  "https://pipedapi.moomoo.me",
  "https://api.piped.projectsegfau.lt",
  "https://pipedapi.adminforge.de",
  "https://pipedapi.drgns.space",
  "https://api.piped.yt.lo",
  "https://piped-api.lunar.icu",
  "https://pipedapi.system41.de",
  "https://pipedapi.r4fo.com",
  "https://api.piped.nocensor.rest"
];

export default function App() {
  const [apiKey, setApiKey] = useState('');
  const [showSettings, setShowSettings] = useState(false);
  const [query, setQuery] = useState('');
  const [viewMode, setViewMode] = useState('search'); 
  const [channels, setChannels] = useState([]);
  const [loading, setLoading] = useState(false);
  const [channelVideos, setChannelVideos] = useState([]);
  const [selectedChannel, setSelectedChannel] = useState(null);
  const [nextPageToken, setNextPageToken] = useState(null);
  
  const [transcriptModal, setTranscriptModal] = useState({ 
    isOpen: false, videoId: null, title: '', content: '', loading: false, status: '', mode: 'server' 
  });

  useEffect(() => {
    const k = localStorage.getItem('yt_api_key');
    if(k) setApiKey(k); else setShowSettings(true);
  }, []);

  useEffect(() => {
    if(apiKey) localStorage.setItem('yt_api_key', apiKey);
  }, [apiKey]);

  const decodeHtml = (h) => { try { const t = document.createElement("textarea"); t.innerHTML = h; return t.value; } catch(e){return h;} };

  const searchChannels = async (e) => {
    e.preventDefault(); if(!query.trim()) return; setLoading(true); setViewMode('search');
    try {
      const res = await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=12&q=${encodeURIComponent(query)}&type=channel&key=${apiKey}`);
      const data = await res.json(); setChannels(data.items||[]);
    } catch(e){} finally { setLoading(false); }
  };

  const handleChannelClick = async (cid, ctitle) => {
    setLoading(true);
    try {
      const res = await fetch(`https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=${cid}&key=${apiKey}`);
      const data = await res.json();
      if(data.items?.[0]) {
        const uid = data.items[0].contentDetails.relatedPlaylists.uploads;
        setSelectedChannel({id:cid, title:ctitle, uploadsId:uid});
        const vRes = await fetch(`https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=12&playlistId=${uid}&key=${apiKey}`);
        const vData = await vRes.json();
        setNextPageToken(vData.nextPageToken);
        setChannelVideos(vData.items||[]);
        setViewMode('videos');
      }
    } catch(e){} finally { setLoading(false); }
  };

  const loadMore = async () => {
    if(!selectedChannel || !nextPageToken) return;
    try {
      const res = await fetch(`https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=12&playlistId=${selectedChannel.uploadsId}&pageToken=${nextPageToken}&key=${apiKey}`);
      const data = await res.json();
      setNextPageToken(data.nextPageToken);
      setChannelVideos(prev => [...prev, ...data.items]);
    } catch(e){}
  };

  // ----------------------------------------------------------------
  // [전략 1] Swarm Network (Piped API 분산 처리)
  // ----------------------------------------------------------------
  const fetchSwarmTranscript = async (videoId, updateStatus) => {
    const nodes = [...SWARM_NODES].sort(() => 0.5 - Math.random());
    
    for (const [i, node] of nodes.entries()) {
      try {
        updateStatus(`우회 경로 탐색 중 (${i+1}/${nodes.length})...`);
        const controller = new AbortController();
        const id = setTimeout(() => controller.abort(), 2000); // 2초 타임아웃 (빠른 전환)
        
        const res = await fetch(`${node}/streams/${videoId}`, { signal: controller.signal });
        clearTimeout(id);

        if (res.ok) {
          const data = await res.json();
          const subtitles = data.subtitles || [];
          
          const track = subtitles.find(s => s.code === 'ko' && !s.autoGenerated) ||
                        subtitles.find(s => s.code === 'en' && !s.autoGenerated) ||
                        subtitles.find(s => s.code === 'ko') ||
                        subtitles[0];
          
          if (track) {
            const subRes = await fetch(track.url);
            if (subRes.ok) {
              let text = await subRes.text();
              text = text.replace(/WEBVTT/g, '').replace(/\d{2}:\d{2}.*?\n/g, '').replace(/<[^>]+>/g, '').replace(/\n+/g, ' ').trim();
              return { text, source: new URL(node).hostname };
            }
          }
        }
      } catch (e) { continue; }
    }
    throw new Error('Swarm Failed');
  };

  // ----------------------------------------------------------------
  // [전략 2] Direct Parsing (최후의 수단)
  // ----------------------------------------------------------------
  const fetchDirectTranscript = async (videoId, updateStatus) => {
    updateStatus('직접 파싱 시도 중...');
    const PROXY = 'https://corsproxy.io/?';
    
    const html = await (await fetch(`${PROXY}https://www.youtube.com/watch?v=${videoId}`)).text();
    const match = html.match(/"captionTracks":(\[.*?\])/);
    
    if (match) {
      const tracks = JSON.parse(match[1]);
      const track = tracks.find(t => t.languageCode === 'ko') || tracks.find(t => t.languageCode === 'en') || tracks[0];
      const xml = await (await fetch(`${PROXY}${encodeURIComponent(track.baseUrl)}`)).text();
      
      return {
        text: xml.replace(/<text.*?>(.*?)<\/text>/g, '$1 ').replace(/<[^>]+>/g, '').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim(),
        source: 'Direct Parser'
      };
    }
    throw new Error('Direct Failed');
  };

  // [메인] 자막 요청 오케스트레이터
  const getTranscript = async (title, videoId) => {
    setTranscriptModal({ isOpen: true, videoId, title, content: '', loading: true, status: '서버 요청 중...', mode: 'server' });
    
    try {
      // 1단계: Netlify 서버 시도
      const res = await fetch(`/.netlify/functions/transcript?videoId=${videoId}`);
      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          setTranscriptModal(p => ({...p, loading: false, content: data.transcript, status: `완료 (Server: ${data.lang})`, mode: 'success' }));
          return;
        }
      }
      throw new Error('Server 500');
    } catch (serverErr) {
      // 2단계: Swarm & Direct Fallback
      console.warn("Server failed, switching to Swarm...", serverErr);
      setTranscriptModal(p => ({...p, status: '서버 차단됨. 우회 경로 진입...', mode: 'network' }));
      
      try {
        // Swarm 먼저 시도
        const result = await fetchSwarmTranscript(videoId, (msg) => setTranscriptModal(p => ({...p, status: msg})));
        setTranscriptModal(p => ({...p, loading: false, content: result.text, status: `완료 (Swarm: ${result.source})`, mode: 'success' }));
      } catch (swarmErr) {
        // 실패 시 Direct 시도
        try {
          const directResult = await fetchDirectTranscript(videoId, (msg) => setTranscriptModal(p => ({...p, status: msg})));
          setTranscriptModal(p => ({...p, loading: false, content: directResult.text, status: `완료 (Direct)`, mode: 'success' }));
        } catch (finalErr) {
          setTranscriptModal(p => ({...p, loading: false, content: '자막을 가져올 수 없습니다.\n\n원인: 이 영상에는 자막이 없거나, 모든 접근 경로가 차단되었습니다.', status: '실패', mode: 'error' }));
        }
      }
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 font-sans text-gray-900">
      <header className="bg-white shadow-sm sticky top-0 z-20 h-16 flex items-center px-4 gap-4">
        <div className="flex items-center gap-2 text-red-600 font-bold text-lg cursor-pointer" onClick={() => window.location.reload()}>
          <Youtube fill="currentColor"/> Explorer
        </div>
        <div className="flex-1"></div>
        <button onClick={() => setShowSettings(!showSettings)} className="p-2 hover:bg-gray-100 rounded-full"><Settings size={24}/></button>
      </header>

      {showSettings && (
        <div className="bg-gray-800 p-4 text-white flex justify-center"><div className="flex gap-2 w-full max-w-2xl"><input className="text-black flex-1 p-2 rounded" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="YouTube API Key"/><button onClick={()=>setShowSettings(false)} className="bg-yellow-600 px-4 rounded">닫기</button></div></div>
      )}

      {transcriptModal.isOpen && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-2xl h-[70vh] flex flex-col">
            <div className="p-4 border-b flex justify-between items-center">
              <h3 className="font-bold truncate pr-4">{transcriptModal.title}</h3>
              <button onClick={()=>setTranscriptModal(p=>({...p, isOpen:false}))}><X/></button>
            </div>
            <div className="flex-1 p-4 overflow-auto relative">
              {transcriptModal.loading ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-white text-center">
                  <Loader2 className="animate-spin text-blue-600 mb-4" size={40}/>
                  <p className="text-sm font-bold text-gray-700 mb-1">{transcriptModal.status}</p>
                  {transcriptModal.mode === 'network' && <p className="text-xs text-gray-500">서버가 응답하지 않아 분산 네트워크를 탐색합니다.</p>}
                </div>
              ) : (
                <>
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{transcriptModal.content}</p>
                  <div className={`text-xs text-right mt-4 flex justify-end items-center gap-1 font-medium ${transcriptModal.mode === 'error' ? 'text-red-600' : 'text-green-600'}`}>
                    {transcriptModal.mode === 'error' ? <ServerCrash size={14}/> : <ShieldCheck size={14}/>} {transcriptModal.status}
                  </div>
                </>
              )}
            </div>
            <div className="p-4 border-t text-right">
              <button onClick={() => navigator.clipboard.writeText(transcriptModal.content)} className="px-4 py-2 bg-gray-900 text-white rounded text-sm flex items-center gap-2 ml-auto"><Copy size={14}/> 복사하기</button>
            </div>
          </div>
        </div>
      )}

      <main className="max-w-7xl mx-auto p-4">
        {!apiKey && <div className="text-center py-10 text-gray-500">설정에서 API 키를 입력해주세요.</div>}
        {apiKey && (
          <>
            <form onSubmit={searchChannels} className="flex gap-2 max-w-lg mx-auto mb-8"><input value={query} onChange={e=>setQuery(e.target.value)} className="flex-1 p-3 rounded-full border shadow-sm" placeholder="채널 검색"/><button className="bg-red-600 text-white px-6 rounded-full">검색</button></form>
            {loading && <div className="flex justify-center py-10"><Loader2 className="animate-spin text-red-600" size={40}/></div>}
            {viewMode === 'search' && !loading && <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{channels.map(c => (<div key={c.id.channelId} onClick={()=>handleChannelClick(c.id.channelId, decodeHtml(c.snippet.title))} className="bg-white p-4 rounded-xl shadow cursor-pointer hover:shadow-lg text-center"><img src={c.snippet.thumbnails.medium.url} className="w-20 h-20 rounded-full mx-auto mb-2"/><h3 className="font-bold line-clamp-1">{decodeHtml(c.snippet.title)}</h3></div>))}</div>}
            {viewMode === 'videos' && !loading && <div><button onClick={()=>setViewMode('search')} className="mb-4 flex items-center gap-1 text-sm font-bold"><ChevronLeft size={16}/> 뒤로가기</button><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{channelVideos.map(v => (<div key={v.id} className="bg-white rounded-xl shadow overflow-hidden"><div className="aspect-video bg-gray-200 relative"><img src={v.snippet.thumbnails.medium?.url} className="w-full h-full object-cover"/><div className="absolute inset-0 flex items-center justify-center bg-black/10 opacity-0 hover:opacity-100 transition-opacity"><Play className="text-white" fill="white"/></div></div><div className="p-3"><h3 className="font-bold text-sm line-clamp-2 mb-3 h-10">{decodeHtml(v.snippet.title)}</h3><button onClick={()=>getTranscript(decodeHtml(v.snippet.title), v.snippet.resourceId.videoId)} className="w-full py-2 bg-blue-50 text-blue-600 rounded text-xs font-bold hover:bg-blue-100 flex items-center justify-center gap-1"><Globe size={12}/> 자막 추출</button></div></div>))}</div>{nextPageToken && <div className="text-center mt-6"><button onClick={loadMore} className="px-6 py-2 bg-white border rounded-full text-sm">더 보기</button></div>}</div>}
          </>
        )}
      </main>
    </div>
  );
}